version: "3"

dotenv:
  - ".env"
vars:
  PLUGIN_ID: "typst-mate"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  check:
    cmds:
      - bun update --latest
      - bunx biome check

  placestatic:
    vars:
      PLUGIN_DIR: "{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}"
      version:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - mkdir -p "{{.PLUGIN_DIR}}"
      - touch '{{.PLUGIN_DIR}}/.hotreload'
      - cp manifest.json '{{.PLUGIN_DIR}}'
    desc: "Copy static files to plugin directory"
  wasm:
    vars:
      PLUGIN_DIR: "{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}"
      version:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - wasm-pack build wasm --target web --dev --out-dir ../pkg
      - rm -f '{{.PLUGIN_DIR}}/'*.wasm
      - mv './pkg/typst_wasm_bg.wasm' '{{.PLUGIN_DIR}}/typst-{{.version}}.wasm'
    desc: "Build WASM file and copy to plugin directory"
  wasm-release:
    vars:
      PLUGIN_DIR: "{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}"
      version:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - wasm-pack build wasm --target web --release --out-dir ../pkg
      - rm -f '{{.PLUGIN_DIR}}/'*.wasm
      - mv './pkg/typst_wasm_bg.wasm' '{{.PLUGIN_DIR}}/typst-{{.version}}.wasm'
    desc: "Build WASM file and copy to plugin directory"
  dev:
    cmds:
      - bunx --bun vite build -w -m development --outDir '{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}'
    desc: "Build in development mode and copy to plugin directory"

  fetch_unicode_math_table:
    cmds:
      - curl -sL https://raw.githubusercontent.com/wspr/unicode-math/master/unicode-math-table.tex -o wasm/src/tools/unicode-math-table.tex
    desc: "Fetch latest unicode-math-table.tex from GitHub"
    status:
      - 'test "{{.UPDATE}}" != "true"'
      - "test -f wasm/src/tools/unicode-math-table.tex"

  update_symbols:
    deps:
      - fetch_unicode_math_table
    cmds:
      - cd wasm && cargo run --bin symbol
    desc: "Update symbols"

  release:
    vars:
      tag:
        sh: "bun scripts/version.ts --type {{.TYPE}}"
    cmds:
      - git add manifest.json versions.json
      - 'git commit -m "release: {{.tag}}"'
      - git tag "{{.tag}}"
      - git push
      - git push origin "{{.tag}}"
      - task placestatic
    preconditions:
      - sh: "[ {{.TYPE}} != '' ]"
    desc: "e.g. task release TYPE=major | TYPE=minor | TYPE=patch | TYPE=mock"

  re-release:
    vars:
      tag:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - cmd: gh release delete "{{.tag}}" --yes --cleanup-tag
        ignore_error: true
      - cmd: git push origin --delete "{{.tag}}"
        ignore_error: true
      - cmd: git tag -d "{{.tag}}"
        ignore_error: true
      - git tag "{{.tag}}"
      - git push origin "{{.tag}}"
      - echo "Tag {{.tag}} re-pushed. Workflow will be triggered."
