version: "3"

vars:
  PLUGIN_ID: "typst-mate"

dotenv:
  - ".env"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  check:
    cmds:
      - bun update --latest
      - bunx biome check

  putstatic:
    vars:
      PLUGIN_DIR: "{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}"
      version:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - touch '{{.PLUGIN_DIR}}/.hotreload'
      - cp manifest.json '{{.PLUGIN_DIR}}'
      - cp pkg/typst_wasm_bg.wasm '{{.PLUGIN_DIR}}'
      - mv '{{.PLUGIN_DIR}}/typst_wasm_bg.wasm' '{{.PLUGIN_DIR}}/typst-{{.version}}.wasm'
  wasm:
    vars:
      PLUGIN_DIR: "{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}"
      version:
        sh: "bun scripts/version.ts --type mock"
    cmds:
      - wasm-pack build wasm --target web --dev --out-dir ../pkg
      - mv './pkg/typst_wasm_bg.wasm' '{{.PLUGIN_DIR}}/typst-{{.version}}.wasm'
  dev: bunx --bun vite build -w -m development --outDir '{{.CONFIG_DIR}}/plugins/{{.PLUGIN_ID}}'
  build:
    cmds:
      - bun run wasm
      - mv pkg/typst_wasm_bg.wasm typst.wasm
      - bun run build
      - rm typst.wasm

  commit:
    cmds:
      - bun run check
      - git add .
      - git commit -m "{{.MESSAGE}}"
    preconditions:
      - sh: "[ {{.MESSAGE}} != '' ]"
    desc: "e.g. task commit MESSAGE=update"

  release:
    vars:
      tag:
        sh: "bun scripts/version.ts --type {{.TYPE}}"
    cmds:
      - git add manifest.json versions.json
      - git commit -m "update version {{.tag}}"
      - git tag "{{.tag}}"
      - git push
      - git push origin "{{.tag}}"
    preconditions:
      - sh: "[ {{.TYPE}} != '' ]"
    desc: "e.g. task release TYPE=patch"
